[package]
name = "agemda"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "agmd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.31", features = ["derive"] }
dirs = "6.0.0"
fjall = "2.6.5"
ignore = "0.4.23"
nom = "8.0.0"
postcard = { version = "1.1.1", features = ["alloc"] }
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
uuid = { version = "1.14.0", features = ["v4"] }

